<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AcSoft.Domain\AcSoft.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Abstractions\Services\" />
    <Folder Include="Features\WorkOrders\Validators\" />
    <Folder Include="Features\WorkOrders\Queries\" />
    <Folder Include="UseCases\" />
  </ItemGroup>

</Project>
